### ISSUE TITLE
[cob_script_server] calculate_point_time() fails for mimic joints

### ISSUE THREAD

**Issue by fmessmer** [4am-robotics/cob_command_tools#166]
When using the dashboard to move the SDH - which has mimic joints - the following error occurs within ```cob_script_server```'s ```calculate_point_time``` function due to a mismatch of the (mimic) joints

```
[INFO] [WallTime: 1484144039.369393] [40.880000] Move <<gripper>> to <<home>>
Unhandled exception in thread started by <bound method simple_script_server.move of <simple_script_server.simple_script_server.simple_script_server instance at 0x7f9b8c11bbd8>>
Traceback (most recent call last):
  File "/home/fxm/projects/indigo/care-o-bot/src/cob_command_tools/cob_script_server/src/simple_script_server/simple_script_server.py", line 331, in move
    return self.move_traj(component_name,parameter_name,blocking)
  File "/home/fxm/projects/indigo/care-o-bot/src/cob_command_tools/cob_script_server/src/simple_script_server/simple_script_server.py", line 588, in move_traj
    (traj_msg, error_code) = self.compose_trajectory(component_name, parameter_name)
  File "/home/fxm/projects/indigo/care-o-bot/src/cob_command_tools/cob_script_server/src/simple_script_server/simple_script_server.py", line 558, in compose_trajectory
    point_time = self.calculate_point_time(component_name, start_pos, point, default_vel)
  File "/home/fxm/projects/indigo/care-o-bot/src/cob_command_tools/cob_script_server/src/simple_script_server/simple_script_server.py", line 569, in calculate_point_time
    d_max = max(list(abs(numpy.array(start_pos) - numpy.array(end_pos))))
ValueError: operands could not be broadcast together with shapes (8,) (7,)
```

**Comment by fmessmer** [comment]
#167 solves this
