### ISSUE TITLE
[cpu_monitor] acquire all stats/data from netdata

### ISSUE THREAD

**Issue by benmaidel** [4am-robotics/cob_command_tools#313]
Since netdata already collects all the data that cpu_monitor might need, and cpu_monitor already uses some stats from netdata, we should move to getting all the data entirely from netdata.

**Comment by pgehring** [comment]
netdata installation was not successfull with the following command:
`bash <(curl -Ss https://my-netdata.io/kickstart.sh) all --dont-wait`
This installed the service from the `apt` sources. 

After removing the apt sources in 
`/etc/apt/sources.list.d/`
the command
`curl https://my-netdata.io/kickstart.sh > /tmp/netdata-kickstart.sh && sh /tmp/netdata-kickstart.sh`
succeeded to install. This is also the recommended command from the netdata documentation.
The options `curl https://my-netdata.io/kickstart.sh > /tmp/netdata-kickstart.sh && sh /tmp/netdata-kickstart.sh --non-interactive --static-only` have to be added to successfully install netdata in the `setup_cob4` `kickstart-robot.sh`

**Comment by pgehring** [comment]
The cpu_monitor is currently not functional on the NUC gen 11. This results in the following diagnotics errors:
![CPU Info Errors](https://user-images.githubusercontent.com/43449655/156406112-0e844403-d492-43cc-b92b-ca31c62d7976.png)
The node is carshing with the following errors:
```
process[ntp_monitor_t2_196012_3168278479661393458_t2-3]: started with pid [196052]
process[net_monitor_t2_196012_2422853568442527902_t2-4]: started with pid [196053]
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/timer.py", line 237, in run
    self._callback(TimerEvent(last_expected, last_real, current_expected, current_real, last_duration))
  File "/u/robot/git/robot_ws/src/cob_command_tools/cob_monitoring/src/ntp_monitor.py", line 101, in publish_diagnostics
    self.diag_pub.publish(self.msg)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 882, in publish
    self.impl.publish(data)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 1066, in publish
    serialize_message(b, self.seq, message)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/msg.py", line 152, in serialize_message
    msg.serialize(b)
  File "/opt/ros/noetic/lib/python3/dist-packages/diagnostic_msgs/msg/_DiagnosticArray.py", line 141, in serialize
    _x = _x.encode('utf-8')
AttributeError: 'bytes' object has no attribute 'encode'
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/timer.py", line 237, in run
    self._callback(TimerEvent(last_expected, last_real, current_expected, current_real, last_duration))
  File "/u/robot/git/robot_ws/src/cob_command_tools/cob_monitoring/src/cpu_monitor.py", line 825, in publish_stats
    self._diag_pub.publish(msg)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 882, in publish
    self.impl.publish(data)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 1066, in publish
    serialize_message(b, self.seq, message)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/msg.py", line 152, in serialize_message
    msg.serialize(b)
  File "/opt/ros/noetic/lib/python3/dist-packages/diagnostic_msgs/msg/_DiagnosticArray.py", line 141, in serialize
    _x = _x.encode('utf-8')
AttributeError: 'bytes' object has no attribute 'encode'
```

**Comment by pgehring** [comment]
All the data of the cpu_monitor is now aquired from netdata. This is tested on a fresh NUC setup with the latest netdata installation.
```
roslaunch mojin_bringup base_solo.launch robot:=cob4-14
roslaunch mojin_bringup pc_monitor.launch pc:=b1 diag_hostname:=b1 robot:=cob4-14
```
The ipmi data was also removed since it needs sudo privilages and could also be aquired from netdata (https://learn.netdata.cloud/docs/agent/collectors/freeipmi.plugin) through a plugin. This currently not implemented.
