### ISSUE TITLE
emergency_stop_monitor throws an error after staring bringup

### ISSUE THREAD

**Issue by floweisshardt** [4am-robotics/cob_command_tools#95]
error log after starting bringup:

```
[ERROR] [WallTime: 1429707464.892564] bad callback: <bound method emergency_stop_monitor.new_diagnostics of <__main__.emergency_stop_monitor instance at 0x7f160f6c6a28>>
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 702, in _invoke_callback
    cb(msg)
  File "/u/fmw/git/care-o-bot/src/cob_command_tools/cob_monitoring/src/emergency_stop_monitor.py", line 69, in new_diagnostics
    if ((rospy.get_rostime() - self.last_vel).to_sec() > 1.0):
AttributeError: emergency_stop_monitor instance has no attribute 'last_vel'

[ERROR] [WallTime: 1429707465.392527] bad callback: <bound method emergency_stop_monitor.new_diagnostics of <__main__.emergency_stop_monitor instance at 0x7f160f6c6a28>>
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 702, in _invoke_callback
    cb(msg)
  File "/u/fmw/git/care-o-bot/src/cob_command_tools/cob_monitoring/src/emergency_stop_monitor.py", line 69, in new_diagnostics
    if ((rospy.get_rostime() - self.last_vel).to_sec() > 1.0):
AttributeError: emergency_stop_monitor instance has no attribute 'last_vel'
```

**Comment by fmessmer** [comment]
fixed in https://github.com/ipa320/cob_command_tools/pull/98
